---
channel: edge
apps:
  keypad-app:
    repository: cjramseyer/keypad-app
    target: keypad-app
    image: ghcr.io/cjramseyer/keypad-app/{arch}
  bartender:
    repository: cjramseyer\bartender
    target: bartender
    image: ghcr.io/cjramseyer/tender/{arch}
